<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mybox"
 *
 * Auto generated by Extension Builder 2013-05-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'My Box',
	'description' => 'Box for default configuration',
	'category' => 'plugin',
	'author' => 'Chanthou, chanthou',
	'author_email' => 'chanthou.nim@gmail.com, chanthou.nim@gmail.com',
	'author_company' => 'Cambo-Web-base, Cambo-Web-base',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>